config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get 'pages/about'
  get 'pages/rank'
  get 'pages/beer'

  resources :preferences, only: [:index]
  resources :favorite_teams, only: [:new, :create, :destroy]
  resources :favorite_leagues, only: [:new, :create, :destroy]
  resources :games, only: [:index, :show] do
    resources :prognoses, only: [:new, :create]
    resources :chats, only: [:index, :show] do
      resources :messages, only: :create
    end
  end

  mount ActionCable.server => "/cable"

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :game
  belongs_to :team, optional: true
  has_many :messages, dependent: :destroy
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @game = Game.find(params[:game_id])
    @prognosis = Prognosis.new
    @prog = []
    current_user.prognoses.each { |p| @prog << p if p.game == @game }
  end

  def show
    @chat = Chat.includes(messages: :user).find(params[:id])
  end


end

app/views/chats/index.html.erb
<% content_for :meta_title, "#{@game.team_a.name} vs #{@game.team_b.name} on the #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "Chat about the #{@game.team_a} vs #{@game.team_b} game! Starting time: #{@game.kick_off_time.strftime("%H-%M")} on #{@game.kick_off_time.strftime("%d-%b")}" %>


  <div class="background-pub">


  <div class="title-tables">
    <h2>CHOOSE YOUR TABLE</h2>
  </div>

  <div class="col-md-offset-4 col-md-4 col-sm-offset-3 col-sm-6">

    <% unless @prog.any? %>
      <div class="prog-btn-container">
        <%= render 'prognoses/new' %>
      </div>
    <% else %>
      <div class="prognosis-container text-center">
        <h5>Prediction?</h5>

        <div class="prognosis-score">
          <div class="col-xs-5 no-padding">
            <% if @game.team_a.name.length <= 17 %>
              <p><%= @game.team_a.name %></p>
            <% else %>
              <p><%= @game.team_a.name[0..14] %>...</p>
            <% end %>
          </div>
          <div class="col-xs-2 no-padding">
            <div class="score"> <%= @prog.first.team_a_score %> : <%= @prog.first.team_b_score %></div>
          </div>
          <div class="col-xs-5 no-padding">
            <% if @game.team_b.name.length <= 17 %>
              <p><%= @game.team_b.name %></p>
            <% else %>
              <p><%= @game.team_b.name[0..14] %>...</p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <%= link_to game_chat_path(game_id: @game.id, id: @game.chat_for_team_a), class: "card-tables", id:"first-card-table" do%>
      <div class="card-item">
        <%#= image_tag "table.svg", class:"card-tables-table" %>

        <%= image_tag Team.find(@game.team_a_id).logo, class:"card-tables-logo" %>
      </div>
      <div class="card-team">
        <p><%= Team.find(@game.team_a_id).name %></p>
      </div>
    <% end  %>

    <%= link_to game_chat_path(game_id: @game.id, id: @game.chat_for_team_b), class: "card-tables" do%>
      <div class="card-item">
        <%#= image_tag "table.svg", class:"card-tables-table" %>
        <!-- Logo on Table -->
        <%= image_tag Team.find(@game.team_b_id).logo, class:"card-tables-logo" %>
      </div>
      <div class="card-team">
        <p><%= Team.find(@game.team_b_id).name %></p>
      </div>
    <% end %>


    <%= link_to game_chat_path(game_id: @game.id, id: @game.chat_neutral), class: "card-tables" do%>
      <div class="card-item">
        <%#= image_tag "table.svg", class:"card-tables-table" %>
        <!-- Logo on Table -->
        <%= image_tag "beer.svg", class:"card-tables-beer" %>
      </div>
      <div class="card-team">
        <p>"Stammtisch"</p>
      </div>
    <% end %>
  </div>

</div>

app/views/chats/show.html.erb
<% content_for :meta_title, "Chat about #{@chat.game.team_a.name} vs #{@chat.game.team_b.name} on the #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "Chat about the #{@chat.game.team_a.name} vs #{@chat.game.team_b.name} game! Starting time: #{@chat.game.kick_off_time.strftime("%H-%M")} on #{@chat.game.kick_off_time.strftime("%d-%b")}" %>


<div class="chat-name">
  <% if @chat.team.present? %>
    <%= image_tag @chat.team.logo %> <h2><%= @chat.team.name %> table</h2>
  <% else %>
    <%= image_tag 'beer.svg' %><h2>Stammtisch</h2>
  <% end %>
    <div class="beer-icon">
      <%= link_to pages_beer_path do %>
      <%= image_tag "beer-button.svg", alt: "Beer Button" %>
      <% end  %>
    </div>

</div>


<div class="messages">
 <!-- style="background-image: linear-gradient(-205deg, rgb(255, 255, 255) 0%, rgba(255, 255, 255, 0.91) 50%), url('http://irishpubcompany.com/wp-content/uploads/2015/12/Capture1.jpg');"> -->
  <% @chat.messages.order(created_at: :asc).each do |message| %>
    <%= render "messages/message", message: message, user_is_messages_author: message.user == current_user %>
  <% end %>
</div>


<div id="create-message">
  <%= simple_form_for [@chat.game, @chat, Message.new], html: { style: 'display:flex' },remote: true do |f| %>
    <%= f.input :content, label: false %>

    <%= button_tag :submit, class: "btn btn-round-green" do %>
        <%= image_tag "dpub-arrow-right.png", alt: "Arrow", width: "14px"; %>
    <% end %>
    <%#= f.submit, class:'btn btn-round-green' do %>
  <% end %>

</div>


<%= content_for(:after_js) do %>
  <script>
    function timer() {
      setTimeout(function() {
        window.location='https://www.digital-pub.live/pages/beer'
      }, 7000);
    }
    scrollLastMessageIntoView();
    App['chat_<%= @chat.id %>'] = App.cable.subscriptions.create({ channel: 'ChatsChannel', chat_id: <%= @chat.id %> }, {
      received: (data) => {
        if (data.current_user_id !== <%= current_user.id %>) {
          const messagesContainer = document.querySelector('.messages');
          messagesContainer.insertAdjacentHTML('beforeend', data.message_partial);
          scrollLastMessageIntoView();
          if (data.admin === true) {
            timer()
          }
        }
      }
    })

    if(!!window.performance && window.performance.navigation.type == 2)
    {
        window.location.reload();
    }
  </script>

<% end %>