config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get 'pages/about'
  get 'pages/rank'
  get 'pages/beer'

  resources :preferences, only: [:index]
  resources :favorite_teams, only: [:new, :create, :destroy]
  resources :favorite_leagues, only: [:new, :create, :destroy]
  resources :games, only: [:index, :show] do
    resources :prognoses, only: [:new, :create]
    resources :chats, only: [:index, :show] do
      resources :messages, only: :create
    end
  end

  mount ActionCable.server => "/cable"

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :game
  belongs_to :team, optional: true
  has_many :messages, dependent: :destroy
end

app/models/favorite_league.rb
class FavoriteLeague < ApplicationRecord
  belongs_to :league
  belongs_to :user
end

app/models/favorite_team.rb
class FavoriteTeam < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team_a, class_name: 'Team'
  belongs_to :team_b, class_name: 'Team'
  belongs_to :league
  has_many :chats, dependent: :destroy
  has_many :prognoses
  validates :kick_off_time, presence: true

  after_create :generate_chat

  def generate_chat
    #create Chat for Team A
    chat_a = Chat.create(game_id: self.id, team_id: self.team_a_id)
    chat_a.save
    #create Chat for Team B
    chat_b = Chat.create(game_id: self.id, team_id: self.team_b_id)
    chat_a.save
    #create neutral Chat
    chat_c = Chat.create(game_id: self.id)
    chat_a.save
  end

  def chat_for_team_a
    chats.find_by(team_id: team_a_id)
  end

  def chat_for_team_b
    chats.find_by(team_id: team_b_id)
  end

  def chat_neutral
    chats.find_by(team_id: nil)
  end
end

app/models/league.rb
class League < ApplicationRecord
  has_many :favorite_leagues, dependent: :destroy
  has_many :games
  validates :name, presence: true
  validates :logo, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :chat
  validates :content, presence: true, allow_blank: false
  after_create :broadcast_message

  def from?(some_user)
    user == some_user
  end

  def broadcast_message
    ActionCable.server.broadcast("chat_#{chat.id}", {
      message_partial: ApplicationController.renderer.render(
        partial: "messages/message",
        locals: { message: self, user_is_messages_author: false }
      ),
      current_user_id: user&.id,
      admin: user&.admin
    })
  end
end

app/models/prognosis.rb
class Prognosis < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :favorite_teams, dependent: :destroy
  has_many :games_as_team_a, class_name: 'Game', foreign_key: :team_a
  has_many :games_as_team_b, class_name: 'Game', foreign_key: :team_b
  has_many :chats

  validates :name, presence: true
  validates :logo, presence: true

  def games
    Game.where(team_a: self).or(Game.where(team_b: self))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages, dependent: :destroy
  has_many :chats, through: :messages
  has_many :favorite_leagues, dependent: :destroy
  has_many :favorite_teams, dependent: :destroy
  has_many :prognoses, dependent: :destroy
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @game = Game.find(params[:game_id])
    @prognosis = Prognosis.new
    @prog = []
    current_user.prognoses.each { |p| @prog << p if p.game == @game }
  end

  def show
    @chat = Chat.includes(messages: :user).find(params[:id])
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @date = Date.today
    @time = Time.now.utc
    @max_date = @date + 5
    @games_1 = []
    @games_2 = []

    @league = League.find(params[:league]) || League.first

    @games = Game.where(league: @league)

    @games.each do |g|
      #old_game = g.kick_off_time - 60.minutes

      # TODAYS NEXT GAMES
      if g.chats.first.online == false && g.kick_off_time.to_date == @date && g.kick_off_time > Time.now
        @games_2 << g
      # NEXT 5 DAYS GAMES
      elsif g.kick_off_time.to_date > @date && g.kick_off_time.to_date <= @max_date
        @games_2 << g
      # ONLINE GAMES
      elsif g.chats.first.online == true
        @games_1 << g
      end
    @games_2.sort! { |a,b| a.kick_off_time <=> b.kick_off_time }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(params_message)
    @chat = Chat.find(params[:chat_id])
    @message.chat = @chat
    @message.user = current_user
    if @message.save
      respond_to do |format|
        format.html { redirect_to game_chat_path(@chat) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render "chats/show" }
        format.js
      end
    end
  end

  private

  def params_message
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]

  def home
    @leagues = League.all
    @favteams = FavoriteTeam.where(user: current_user)
    @games = []
    @favteams.each do |t|
      t.team.games.each do |g|
        @games << g if g.kick_off_time >= Date.today
      end
    end
    @games.sort! { |a,b| a.kick_off_time <=> b.kick_off_time }
  end

  def rank
    @users = User.all
    @rank = []

    @users.each do |u|
      if u.score > 0
        @rank << u
      end
    end
    @rank.sort! { |a,b| b.score <=> a.score }
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController

  def index
    @favoriteteams = FavoriteTeam.where(user_id: current_user.id)
    @favoriteleagues = FavoriteLeague.where(user_id: current_user.id)
    @favoriteleague = FavoriteLeague.new
    @favoriteteam = FavoriteTeam.new
  end
end

app/controllers/prognoses_controller.rb
class PrognosesController < ApplicationController
  def new
    @game = Game.find(params[:id])
    @prognosis = Prognosis.new
  end

  def create
    @game = Game.find(params[:game_id])
    @prognosis = Prognosis.new(params_prognosis)
    @prognosis.game = @game
    @prognosis.user = current_user
    @prognosis.save
    redirect_to game_chats_path
  end

  private

  def params_prognosis
    params.require(:prognosis).permit(:team_a_score, :team_b_score)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    preferences_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="theme-color" content=#0D730A />

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"  %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="wrapper-about">
  <div class="text-container">

    <div class="text-content">
      <h4>What is the Digital Pub?</h4>

      <div class="text-justify">

        <p>Imagine you want to watch a game tonight, but you don't have anybody to watch it with. And what is the fun in watching a game when you can't discuss the coach's decision about bringing their best player only in the last minutes or if you can't bitch about the referee and how obvious it is that he was paid off by the other team?</p>

        <p>Fear no more! The <strong>Digital Pub</strong> has found the solution: an online chat where you can talk about your favorite games with other fans. Enter the Digital Pub and decide at which table you want to sit: at one of the 2 fan tables or at the 'Stammtisch', if your heart swings both ways.</p>

        <p>Register now and set your favorite teams and leagues in your settings, and make sure you don't miss any games! Enjoy :)</p>

        <p><em>Lucca, Daniel, Mario & Amélie @Le Wagon! </em></p>

      </div>
    </div>

  </div>
</div>

app/views/pages/beer.html.erb
<div class="beer">
  <div id="sign-container">
    <div class="sign">
      <div class="jackpots">Goal!</div>
    </div>
  </div>


  <div id="beer-container">
    <div class="pour">
    </div>
    <div id="beaker">
      <div class="beer-foam">
        <div class="foam-1"></div>
        <div class="foam-2"></div>
        <div class="foam-3"></div>
        <div class="foam-4"></div>
        <div class="foam-5"></div>
        <div class="foam-6"></div>
        <div class="foam-7"></div>
      </div>

      <div id="liquid">
        <div class="bubble bubble1"></div>
        <div class="bubble bubble2"></div>
        <div class="bubble bubble3"></div>
        <div class="bubble bubble4"></div>
        <div class="bubble bubble5"></div>
      </div>
    </div>
  </div>
  <div>
    <h4 class="tip">Tap to chug your beer!</h4>
  </div>
</div>


<%= javascript_pack_tag 'beer' %>

app/views/pages/home.html.erb
<% if current_user.present? %>

  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.27) 0%, rgba(0,0,0,0.6) 50%), url('https://images.pexels.com/photos/8590/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=650&w=940')">
    <div class='text-center'>
      <h1>Digital Pub</h1>
    </div>
  </div>

  <% if current_user.favorite_teams.any? %>

    <div class="top-games">
      <div class="title">
        <h2>MY TOP GAMES</h2>
      </div>

      <div class="col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4">
        <div class="game-list">
        <% @games[0..2].each do |g| %>

          <% if g.chats.first.online %>

            <%= link_to game_chats_path(g) do %>
              <div class='game-item'>
                <div class="col-xs-5 team-name text-center">
                  <div class="logo" style="background-image: url('<%= g.team_a.logo %>')"></div>
                </div>

                <div class="col-xs-2 datetime text-center">
                    <p class='text-red'><strong>Live</strong></p>
                  <p><%= g.kick_off_time.strftime("%H:%M") %></p>
                </div>

                <div class="col-xs-5 team-name text-center">
                  <div class="logo" style="background-image: url('<%= g.team_b.logo %>')"></div>
                </div>
              </div>
            <% end %>

          <% else %>

            <div class="no-click-game">
              <div class='game-item'>
                <div class="col-xs-5 team-name text-center">
                  <div class="logo" style="background-image: url('<%= g.team_a.logo %>')"></div>
                </div>

                <div class="col-xs-2 datetime text-center">
                  <% if g.kick_off_time.to_date == Date.today %>
                    <p><strong>Today</strong></p>
                  <% elsif g.kick_off_time.to_date == Date.tomorrow %>
                    <p><strong>Tomorrow</strong></p>
                  <% else %>
                    <p><strong><%= g.kick_off_time.strftime("%d-%b") %></strong></p>
                  <% end %>
                  <p  style="color: rgb(120,120,120);"><%= g.kick_off_time.strftime("%H:%M") %></p>
                </div>

                <div class="col-xs-5 team-name text-center">
                  <div class="logo" style="background-image: url('<%= g.team_b.logo %>')"></div>
                </div>
              </div>
            </div>

          <% end %>
        <% end %>
        </div>
      </div>

    </div>

  <% end %>

  <div class="leagues">
    <div class="title">
      <h2>CHOOSE YOUR LEAGUE</h2>
    </div>

    <div class="col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4">
      <div class="league-list">
        <% @leagues.each do |l| %>
        <div class="col-xs-3">
          <div class="league-item" style="background-image: url('<%= l.logo %>') ">
            <%= link_to '', games_path(league: l) %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

<% else %>

  <div class="banner welcome-banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.27) 0%, rgba(0,0,0,0.6) 50%), url('https://images.pexels.com/photos/8590/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=650&w=940')">
    <div class='text-center'>
      <h1>Digital Pub</h1>
      <p>Chat about your favorite games</p>
    </div>
  </div>

  <div class="welcome">
    <div class="title">
      <h2>WELCOME TO THE DIGITAL PUB</h2>
    </div>

    <div class="welcome-icons">
      <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval='3000'>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <div class="icon-group">
              <div class="text-center">
                <%= image_tag "bar.svg", alt: "bar doors", width: "60px"; %>
                <h6><strong>LOG IN</strong></h6>
              </div>
              <br>
              <p>Sign up or log in to the Digital Pub</p>
            </div>
          </div>

          <div class="item">
            <div class="icon-group">
              <div class="text-center">
                <%= image_tag "soccer-ball.svg", alt: "football", width: "60px"; %>
                <h6><strong>CHOOSE YOUR GAME</strong></h6>
              </div>
              <br>
              <p>Select the game your watching</p>
            </div>
          </div>

          <div class="item">
            <div class="icon-group">
              <div class="text-center">
                <%= image_tag "chat.svg", alt: "chat", width: "60px"; %>
                <h6><strong>CHAT</strong></h6>
              </div>
              <br>
              <p>Chat with fans from all around the world</p>
            </div>
          </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left">
            <%= image_tag "dpub-arrow.png", alt: "Back arrow", width: "14px"; %>
          </span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-left">
            <%= image_tag "dpub-arrow-right.png", alt: "Back arrow", width: "14px"; %>
          </span>
          <span class="sr-only">Next</span>
        </a>
    <div class="btn-wrapper">
      <div class="col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4">
        <div class="welcome-text">
          <%= link_to 'Sign up', new_user_registration_path, class:'btn-digital-pub-green ' %>
          <%= link_to 'Log in', new_user_session_path, class:'btn-digital-pub-green' %>
        </div>
      </div>
    </div>
      </div>
    </div>

  </div>

<% end %>

app/views/pages/rank.html.erb
<% i = 1 %>

<div class="container">
  <div class="rank-container rank-margin">

    <div class="row margin-bottom">

      <div class="col-xs-3">
        <h5><strong>Rank</strong></h5>
      </div>
      <div class="col-xs-6">
        <h5><strong>Nickname</strong></h5>
      </div>
      <div class="col-xs-3 midle">
        <h5><strong>Points</strong></h5>
      </div>
    </div>


    <div class="rank-body">

      <% @rank.each do |u| %>

        <div class="row border">


            <div class="col-xs-3 text-center">

              <%= i %>
            </div>

            <div class="col-xs-6">
              <%= u.username %>
            </div>

            <div class="col-xs-3 text-center">
              <%= u.score %>
            </div>

        </div>
        <% i += 1 %>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= simple_form_for(favorite) do |f| %>
  <%= f.association element %>
  <%= f.button :submit %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div>
    <% if !current_page?("/") %>
    <a href="javascript:history.back()">

      <%#= link_to :back, class: "navbar-wagon-brand" do %>
      <%= image_tag "dpub-arrow.png", alt: "Back arrow", width: "14px"; %>
    </a>
<!--    <i class="fas fa-caret-left"></i> -->
      <%# end %>
    <% end %>
</div>
<div class="navbar-logo">
<%= link_to root_path do %>
  <%= image_tag "dpub-logo.png", alt: "Digital Pub Logo", class: "dpub-logo"; %>
  <!-- <h3 class="navbar-title">Digital Pub</h3> -->
<% end %>
</div>

  <!-- Right Navigation -->
<div class="navbar-wagon-right">
  <% if user_signed_in? %>

  <div class="navbar-wagon-item">
    <div class="dropdown">
      <div data-toggle="dropdown">
      <%= image_tag "dpub-arrow-down.png", alt: "Burger Menu",  height: "14px"; %>
      </div>
      <!--       <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i> -->
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to preferences_path do %>
            <i class="fa fa-user"> </i> <%= t(".profile", default: "Preferences") %>
          <% end %>
        </li>
        <li>
          <%= link_to pages_rank_path do %>
            <i class="fas fa-sort-amount-down"> </i>
            <%= t(".rank", default: "Ranking") %>
          <% end %>
        </li>
        <li>
          <%= link_to pages_about_path do %>
            <i class="fas fa-beer"> </i>  <%= t(".about", default: "About the Digital Pub") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt"> </i>
            <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>

    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

</div>