config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get 'pages/about'
  get 'pages/rank'
  get 'pages/beer'

  resources :preferences, only: [:index]
  resources :favorite_teams, only: [:new, :create, :destroy]
  resources :favorite_leagues, only: [:new, :create, :destroy]
  resources :games, only: [:index, :show] do
    resources :prognoses, only: [:new, :create]
    resources :chats, only: [:index, :show] do
      resources :messages, only: :create
    end
  end

  mount ActionCable.server => "/cable"

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team_a, class_name: 'Team'
  belongs_to :team_b, class_name: 'Team'
  belongs_to :league
  has_many :chats, dependent: :destroy
  has_many :prognoses
  validates :kick_off_time, presence: true

  after_create :generate_chat

  def generate_chat
    #create Chat for Team A
    chat_a = Chat.create(game_id: self.id, team_id: self.team_a_id)
    chat_a.save
    #create Chat for Team B
    chat_b = Chat.create(game_id: self.id, team_id: self.team_b_id)
    chat_a.save
    #create neutral Chat
    chat_c = Chat.create(game_id: self.id)
    chat_a.save
  end

  def chat_for_team_a
    chats.find_by(team_id: team_a_id)
  end

  def chat_for_team_b
    chats.find_by(team_id: team_b_id)
  end

  def chat_neutral
    chats.find_by(team_id: nil)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @date = Date.today
    @time = Time.now.utc
    @max_date = @date + 5
    @games_1 = []
    @games_2 = []

    @league = League.find(params[:league]) || League.first

    @games = Game.where(league: @league)

    @games.each do |g|
      #old_game = g.kick_off_time - 60.minutes

      # TODAYS NEXT GAMES
      if g.chats.first.online == false && g.kick_off_time.to_date == @date && g.kick_off_time > Time.now
        @games_2 << g
      # NEXT 5 DAYS GAMES
      elsif g.kick_off_time.to_date > @date && g.kick_off_time.to_date <= @max_date
        @games_2 << g
      # ONLINE GAMES
      elsif g.chats.first.online == true
        @games_1 << g
      end
    @games_2.sort! { |a,b| a.kick_off_time <=> b.kick_off_time }
    end
  end
end

app/views/games/index.html.erb
<% content_for :meta_title, "#{@league.name} | All coming games on the #{DEFAULT_META["meta_product_name"]}" %>


<div class="leagues-choice">
  <% leagues_array = League.all %>
  <% leagues_array.each do |league| %>
    <div class="<%= "underline" if params[:league].to_i == league.id %>">
      <%= link_to league.name, games_path(league: league) %>
    </div>
  <% end %>
</div>

<div class="games">
  <div class="title today-list">
    <h2>LIVE GAMES</h2>
  </div>

  <% if @games_1.count == 0 %>
    <h2 class='text-center' id='no-live-games'>No live games now</h2>
  <% else %>


  <div class="game-list col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4">
      <% @games_1.each do |g| %>
        <div class='game-item'>
          <%= link_to game_chats_path(g) do %>
            <div class="col-xs-5 team-name text-center">
              <div class="logo" style="background-image: url('<%= g.team_a.logo %>')"></div>
              <% if g.team_a.name.length <= 21 %>
                <p><%= g.team_a.name %></p>
              <% else %>
                <p><%= g.team_a.name[0..17] %>...</p>
              <% end %>
            </div>

            <div class="col-xs-2 datetime font-narrow">
              <% if g.kick_off_time.to_date == Date.today %>
                <!-- <p><strong>Today</strong></p> -->
                <p class='text-red'><strong>Live</strong></p>
              <% elsif g.kick_off_time.to_date == Date.tomorrow %>
                <p><strong>Tomorrow</strong></p>
              <% else %>
                <p><strong><%= g.kick_off_time.strftime("%d-%b") %></strong></p>
              <% end %>
              <p><%= g.kick_off_time.strftime("%H:%M") %></p>
            </div>

            <div class="col-xs-5 team-name text-center">
              <div class="logo" style="background-image: url('<%= g.team_b.logo %>')"></div>
              <% if g.team_b.name.length <= 21 %>
                <p><%= g.team_b.name %></p>
              <% else %>
                <p><%= g.team_b.name[0..17] %>...</p>
              <% end %>
            </div>

          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="title today-list">
    <h2>UPCOMING GAMES</h2>
  </div>
  <div class="game-list col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4">
      <% @games_2.each do |g| %>
    <div class='game-item font-narrow'>

            <div class="col-xs-5 team-name text-center">
              <div class="logo" style="background-image: url('<%= g.team_a.logo %>')"></div>
              <% if g.team_a.name.length <= 21 %>
                <p><%= g.team_a.name %></p>
              <% else %>
                <p><%= g.team_a.name[0..17] %>...</p>
              <% end %>
            </div>

            <div class="col-xs-2 datetime" id="font-narrow">
              <% if g.kick_off_time.to_date == Date.today %>
                <p><strong>Today</strong></p>
              <% elsif g.kick_off_time.to_date == Date.tomorrow %>
                <p><strong>Tomorrow</strong></p>
              <% else %>
                <p><strong><%= g.kick_off_time.strftime("%d-%b") %></strong></p>
              <% end %>
              <p><%= g.kick_off_time.strftime("%H:%M") %></p>
            </div>

            <div class="col-xs-5 team-name text-center">
              <div class="logo" style="background-image: url('<%= g.team_b.logo %>')"></div>
              <% if g.team_b.name.length <= 21 %>
                <p><%= g.team_b.name %></p>
              <% else %>
                <p><%= g.team_b.name[0..17] %>...</p>
              <% end %>
            </div>

    </div>
      <% end %>
  </div>
</div>