config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get 'pages/about'
  get 'pages/rank'
  get 'pages/beer'

  resources :preferences, only: [:index]
  resources :favorite_teams, only: [:new, :create, :destroy]
  resources :favorite_leagues, only: [:new, :create, :destroy]
  resources :games, only: [:index, :show] do
    resources :prognoses, only: [:new, :create]
    resources :chats, only: [:index, :show] do
      resources :messages, only: :create
    end
  end

  mount ActionCable.server => "/cable"

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController

  def index
    @favoriteteams = FavoriteTeam.where(user_id: current_user.id)
    @favoriteleagues = FavoriteLeague.where(user_id: current_user.id)
    @favoriteleague = FavoriteLeague.new
    @favoriteteam = FavoriteTeam.new
  end
end

app/views/preferences/index.html.erb
<div class="title">
  <h2>EDIT YOUR PREFERENCES</h2>
</div>


<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-offset-3 col-sm-6 col-lg-offset-4 col-lg-4">
      <!-- Insert form here -->
      <div class="form-preferences">

<!--           <div class="fav-leagues">
            <h2 class="pref-heading">Favorite leagues:</h2>
            <%#= render "favorite_leagues/new" %>
            <div class="fav-leagues_result">
              <%# if current_user.favorite_leagues.empty? %>
                <p>Currently you don't have any favorite leagues. Add them here</p>
              <%# else %>
                <%# @favoriteleagues.each do |f_league| %>
                  <ul>
                    <li><%#= image_tag f_league.league.logo, class: "logo-small" %> <%#= f_league.league.name %> | <%#= link_to "Remove", favorite_league_path(f_league.id), method: :delete %>
                    </li>
                  </ul>
                <%# end %>
              <%# end %>
            </div>
          </div> -->

          <!-- <hr> -->

        <div class="fav-teams">
          <h2 class="pref-heading">Favorite teams:</h2>

          <div class="fav-leagues_result">
            <% if current_user.favorite_teams.empty? %>
              <p>Currently you don't have any favorite teams. Add them here</p>
            <% else %>
              <% @favoriteteams.each do |f_team| %>
                <div class="row">
                  <div class="fav-item">
                    <div class="col-xs-1 col-logo-fav">
                      <%= image_tag f_team.team.logo, class: "logo-small" %>
                    </div>

                    <div class="col-xs-11 col-name-fav">
                      <%= f_team.team.name %> | <%= link_to "Remove", favorite_team_path(f_team.id), method: :delete %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>

          <h3 class='add-team-title'>Add a team:</h3>
          <%= render "favorite_teams/new" %>

        </div>

      </div>
      <div class="back-button">
        <a href="javascript:history.back()">

          <%#= link_to :back, class: "navbar-wagon-brand" do %>
          <p class="btn btn-digital-pub-green">
            Back
          </p>
        </a>
      </div>
    </div>
  </div>
</div>